### ISSUE TITLE
Resolution not being used in AddWindow constructor?

### ISSUE THREAD

**Issue by LiveAsynchronousVisualizedArchitecture** [ziacko/TinyWindow#16]
At line 1286 it looks like the resolution parameter of the AddWindow function doesn't use the resolution parameter.  Should this be changed to call SetResolution?

**Comment by ziacko** [comment]
ok I just pushed an update to fix that issue in the master branch. this problem has already been fixed in other branches.

**Comment by LiveAsynchronousVisualizedArchitecture** [comment]
very cool thanks!
