### ISSUE TITLE
Docs are in a zip file

### ISSUE THREAD

**Issue by LB--** [ziacko/TinyWindow#2]
Git is not designed to handle zip files, this is a very bad idea. Just put the docs in their own directory and commit them normally like any other code.

**Comment by dacap** [comment]
I think there is a worse problem here. The git repository has 103 commits and I'm still cloning it (70MB and still running :open_mouth:).

To fix this issue I'd recommend to recreate the whole repository from scratch (push --force).

**Comment by ziacko** [comment]
ok the zips have been moved out. I will recreate the whole repo in a few updates when the code is more mature

**Comment by thyrgle** [comment]
If I am understanding this correctly, the reason why it takes so long to clone is in your revision history you have a lot of huge files which are then added to previous commits when cloned. You could also (instead of starting from scratch) purge these files from history using [bfg](https://rtyley.github.io/bfg-repo-cleaner/). This is what [github suggests](https://help.github.com/articles/removing-files-from-a-repository-s-history/#platform-windows).

**Comment by ziacko** [comment]
I keep getting this error. I think it has something to do with a pull request I merged earlier:
 ! [remote rejected] refs/pull/3/head -> refs/pull/3/head (deny updating a hidden ref)
error: failed to push some refs to 'https://github.com/ziacko/TinyWindow.git'

**Comment by apfeltee** [comment]
@ziacko So, I've searched google up and down, and I _think_ the only way to properly solve this is by deleting this repo, deleting the `.git` subdirectory, then re-create the git repo anew? I might be horribly wrong here.

Consider asking the github staff directly, especially in regards with keeping the issues, pull requests, et cetera!

**Comment by LB--** [comment]
There's no need to delete the repo or anything extreme like that. If you rewrite the commit history by modifying each commit so that the zips are unzipped, the old commits which are no longer referenced will eventually be garbage collected. But even before the garbage collection, just fixing the commits should be enough to make the repo smaller for people to download.

Look into this:
https://git-scm.com/docs/git-filter-branch
All you need is a command to unzip the documentation (and then delete the zips), and git can run it on each commit for you. Then you'll have to force push and let everyone know they need to re-clone the repo.

**Comment by ziacko** [comment]
what if I just remove the Docs.zip file as well as the unzipped folder? I'm trying to use unzip in the command line but It of course cannot find it in any commit

**Comment by dacap** [comment]
@ziacko you should remove the Docs.zip file, besides that you should rewrite the repository history avoiding adding huge files (the repository history is huge (more than 70mb), while the downloaded zip of the last commit is just 48kb)

**Comment by dacap** [comment]
You can check this: https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History to rewrite the repo history. After that you should force push your changes:

```
git push origin master --force
```

**Comment by ziacko** [comment]
yeah I've tried rebasing using sourcetree to delete commits but usually the editor doesnt show the correct commit I want to remove and when I try to remove the right one it rejects me

**Comment by ziacko** [comment]
Ive been trying to build an appropriate command but It seems to never find Docs.zip

git filter-branch -f --tree-filter '[-e Docs.zip] && unzip Docs.zip -d ./Docs || echo "not found"' --prune-empty HEAD --all

**Comment by LB--** [comment]
Can you give me the hash of the commit you are working from? I can try doing it on my end with 7zip commandline. I tried forking the repo but it seems the current state is rather messed up, so having the original commit from before I opened this issue would allow me to work with a clean slate.

**Comment by ziacko** [comment]
adef1b8

**Comment by LB--** [comment]
@ziacko are you sure? [I don't see any Docs.zip](https://github.com/ziacko/TinyWindow/tree/adef1b8444969bb9ef036133937d4fd3f4af2a04) like there was before. It also looks like many of the commits are duplicated or something, unless that is how it was before?

**Comment by ziacko** [comment]
88fa9c0 was the last commit that has Docs.zip
the one I just gave you is the commit im working in now

**Comment by dacap** [comment]
There are other files to filter out, like `TinyWidnow/TinyWidnow.sdf` (31mb) from 73876e234fdaeeb811dd9e9990ee4bd2daac8abf (the second commit). I didn't look for other commits after that.

My best advise: start the repo again with a clean first commit.

**Comment by LB--** [comment]
I am having success with extracting the docs in each commit, I can also look into removing other large files like that and updating the gitignore.

**Comment by ziacko** [comment]
yeah that sounds good but I do want to eventually work with earlier versions of the code that I removed which may be needed later. How about I copy this repo to bitbucket and then wipe this one?

**Comment by LB--** [comment]
@ziacko there's no need to go the nuclear option just yet ;)

**Comment by dacap** [comment]
> How about I copy this repo to bitbucket and then wipe this one?

No need for that, if @LB-- rebuild the history, you should be able to pull his branch and replace the official master in this repo.

**Comment by ziacko** [comment]
bfg does show me the largest files:
Docs.zip                                                                                            | edecdaca (13.0 MB), 61840394 (14.8 MB), ...
    TinyWidnow.sdf                                                                                      | 27478621 (30.9 MB), 6c1956a3 (31.8 MB)  
    TinyWindow.pdf                                                                                      | 33dbd581 (1.4 MB), 21d1b1b1 (3.6 MB)  
    TinyWindow.sdf                                                                                      | 9e74fe0e (34.8 MB)  
    classwindowManager.html                                                                             | 3626a059 (1.0 MB)  
    classwindow_manager_a454ebdea6882e0d28888d3d32c1e77ff_a454ebdea6882e0d28888d3d32c1e77ff_icgraph.png | 3e8d63a2 (1.1 MB)  
    classwindow_manager_a699663c4d3deeb5ae9ac2e556aedcb9e_a699663c4d3deeb5ae9ac2e556aedcb9e_icgraph.png | 03b5c3da (2.4 MB)  
    classwindow_manager_a79d9a881fa34afd798a9d8f91a265498_a79d9a881fa34afd798a9d8f91a265498_icgraph.png | a87ead2b (1.2 MB)  
    classwindow_manager_ae80acd0fedac8b6b9a5c19d54702e81e_ae80acd0fedac8b6b9a5c19d54702e81e_icgraph.png | ea8a2f88 (2.4 MB)  
    html.zip                                                                                            | a6c51e5e (6.5 MB)

**Comment by LB--** [comment]
Large files that change infrequently are okay, it's large binary files that change very frequently that are the problem. I've unzipped the docs in https://github.com/LB--/TinyWindow/tree/unzip-docs and I am next going to remove `TinyWindow.sdf` and add it to the `.gitignore` - I think I will also remove the PDF - you can still distribute it with releases but it shouldn't be in each commit. (Really the generated documentation shouldn't be in the repository either, I hadn't realized it was just generated by doxygen when I opened this issue. If it is easy to generate the documentation from any given commit then I'll just remove the documentation altogether - let me know)

**Comment by ziacko** [comment]
yes doxygen just builds ALL the docs automatically (including the PDFs) just keep the doxyfile so people can generate the documentation themselves

**Comment by LB--** [comment]
OKkay, will do. This should dramatically reduce the size of the repository and speed up git.

**Comment by ziacko** [comment]
ok so when you are finished do I pull your work and force push?

**Comment by LB--** [comment]
Yes, I'll tell you which branch to check out from my repo, and you'll run a command like this after you verify that everything is to your liking:
`git push origin name-of-branch:master --force`
For now though, I've got to clean things up :)

**Comment by ziacko** [comment]
thank you so much man. could you teach me this stuff so I don't piss everyone off if this happens again?

**Comment by LB--** [comment]
Sure! I made a similar mistake in the past and have some experience with this situation. I'll write a detailed explanation of how I did this once I finish.

I do need to ask real quick, are there any commits you made after https://github.com/ziacko/TinyWindow/commit/88fa9c0d1df212c3e79a3eada4591387563f4276 that you want to keep? If so, once I finish I will need to rebase them onto my branch so that you don't lose any work. If you have any commit hash to the original master branch before you tried stuff on it that would work too - I think you were at around 103 commits when I originally opened this issue and there are only 97 commits in what I am working on, so 6 commits at least are unaccounted for.

**Comment by ziacko** [comment]
ok these are all after: 
ec370ef
43fd1c6
c233b18
3cfec66
8a533e6
337c62e
d660c7e
2fc4c93 //from another author
6196bdf //merged pull request
901903e
14bd081
136981a
f0515d8
16c0bbe
5fc77b8
aca7230
78c82de
457fff3
00553f8
5666dc2
ab7b3e0
942ed23
784e14f
adef1b8

**Comment by ziacko** [comment]
the ones before:
4ab8d78
d483204
12c89f8 //merged experimental branch
02d03f6 //from experimental branch
0fd1362 // from experimental

//before experimental branch
ee27b7c
7146262
d852aa9

**Comment by LB--** [comment]
Thanks, I double checked and I have the ones from before - I'm currently just cherry-picking the ones from after and manually verifying that everything is okay.

**Comment by LB--** [comment]
@ziacko Okay, please double check and make sure all the commits are there and that the structure of the repository is as you like:
https://github.com/LB--/TinyWindow/commits/finalize-cleanup - the ones that say "with LB" are the ones I cherry-picked manually, I skipped empty commits and skipped merge commits but I did cherry-pick the commits that would have been merged. Double check my work.

If you are happy with it, then this is what you need to do:

``` sh
git remote add LB https://github.com/LB--/TinyWindow.git # add my repository
git fetch LB # fetch the commits
git checkout -b new-master LB/finalize-cleanup # make a branch called new-master based on my work
git push origin --force new-master:master # overwrite master on github using new-master
```

After that, move your project to a safe place as backup, and then re-clone your project from GitHub. This new clone will have a fresh state, so you may want to copy over your IDE files if you have any. Everyone else who works on this project will need to do the same.

If everything turns out well, I'll start writing my detailed report.

**Comment by ziacko** [comment]
according to the dates f40bf2a should be behind bfa4be6

**Comment by LB--** [comment]
> according to the dates f40bf2a should be behind f5be314

I think they are ordered like that because that's when it was merged in. I can fix the order if you want, but I believe it does not matter in this case.

**Comment by ziacko** [comment]
ok it all looks good. turns out f40bf2a is the most recent. do I run your commands in my current working repo?

**Comment by LB--** [comment]
@ziacko Yes, just make sure you understand what each one does first.

**Comment by ziacko** [comment]
ok it's telling me that it could not resolve the hostname new-master: when I try to push

**Comment by LB--** [comment]
> ok it's telling me that it could not resolve the hostname new-master: when I try to push

Oops, I left out the word `origin` - I edited my comment. Try again.

**Comment by LB--** [comment]
It looks like you've done it! :)

> could you teach me this stuff so I don't piss everyone off if this happens again?

Okay, here's an explanation of what I did to fix everything.

> 88fa9c0 was the last commit that has Docs.zip

I started there. I cloned the repo, checked out that commit (`git checkout 88fa9c0`) and then created a branch from it (`git checkout -b unzip-docs`). Then I used [`git filter-branch`](https://git-scm.com/docs/git-filter-branch) to go through each commit and unzip the documentation with 7-zip (because it's what I had installed on my system):

``` sh
git filter-branch -f --tree-filter '("/c/Program Files/7-Zip/7z.exe" x Docs.zip && rm -rf Docs.zi*) || echo no doc zip'
```

That took a while. For commits which did not contain `Docs.zip`, 7-zp error'd out and the command printed `no doc zip` and kept going. The reason I used `Docs.zi*` for rm was because I had seen in some other of your attempts there were some weird files that started with Docs.zip but had a different extension and just contained a commit hash, and I wasn't sure if any of those were in the commits I was working with. Turns out there were not, but I only wanted to have to run that command once. After I inspected everything to see that it was okay, I pushed it to my own fork.

> just keep the doxyfile so people can generate the documentation themselves

For this, I created a new branch and ran filter-branch again:

``` sh
git filter-branch -f --tree-filter '(cd Docs && (rm -rf *.pdf || echo) && (rm -rf html || echo) && cd ..) || ls'
```

For each commit, go it goes into the Docs directory, removes any PDF files, and removes the HTML folder. If either of those actions fails it just echoes nothing. If the Docs folder isn't there, it runs `ls` to show me the list of directories (so I could see if maybe it had a different name or something). It went well so I pushed to my fork again.

> ok these are all after

Once you gave me the list of commits that came after 88fa9c0, I first tried just passing them all to [`git cherry-pick`](https://git-scm.com/docs/git-cherry-pick), but it doesn't like merge commits and I wasn't sure how best to figure out how to use the `-m` option, so I just went through and manually found all the commits I needed to cherry pick and did them indivisually. One of them had conflicts (the one where you unzipped the documentation), and in that case I just made sure the Docs directory only contained the Doxyfile, then I did `git add --all && git status` to double check my work. It looked good, so I ran `git cherry-pick --continue` as it told me to.

At various points during that I kept pushing to my repo so I'd have something to restore from in the event that I corrupted my local copy. After I finished, I checked over everything and then handed it over to you.

If you want more details on any part of this, let me know. This is generally not something that has to be done ever, except in cases like this, but it's still good to be familiar with git enough to know how to do these things.

**Comment by ziacko** [comment]
ok It's done. btw about IDE files I just use CMAKE and then go in and edit the visual studio project settings :)

**Comment by LB--** [comment]
> btw about IDE files I just use CMAKE and then go in and edit the visual studio project settings :)

On that note, I noticed you add each individual file to your `.gitignore` - it would probably be easier to just add the file extensions and the directories you want to ignore ;)

**Comment by ziacko** [comment]
yeah I should. i got too lazy with source tree as all i had to do was drag click a bunch of them and tell git to ignore them

**Comment by LB--** [comment]
Detailed explanation is [above](https://github.com/ziacko/TinyWindow/issues/2#issuecomment-207020809) (we posted at the same time so I'm not sure if you saw it).

@dacap could you verify that cloning the repo is faster now? After all that was the primary goal of all this :)

**Comment by ziacko** [comment]
there are actually still a few duplicates here and there before 8de3785 

should I do a git cherrypick?

**Comment by ziacko** [comment]
I just did a quick clone, It was only 7.64 MB's

**Comment by LB--** [comment]
@ziacko Yes, you'll want to cherry-pick each commit from the merge and not the merge commit itself. If it complains about conflicts, run `git status` to see which files need fixing, and then you just decide what to do to them (edit them so they compile or whatever). Then run `git add --all && git status` to make sure everything is as it should be, and `git cherry-pick --continue`

> I just did a quick clone, It was only 7.64 MB's

Great!

**Comment by LB--** [comment]
@ziacko wait, duplicates or missing commits? If the commits are missing, cherry-pick them, but if they are duplicated, I'd suggest just leaving them alone for now.

**Comment by ziacko** [comment]
they're dupes. what happens if I just leave them? you said earlier that they might be picked up by garbage collection

**Comment by LB--** [comment]
> they're dupes

In that case, just let them be. It's possible to fix them but it's more effort than it's worth. (For reference, if you ever did need to fix them, you would do an interactive rebase - lots of info on Google if you are interested)

**Comment by ziacko** [comment]
It's odd that alot of the dupes are the only ones with tags. Is there somethng I should do with that?

**Comment by dacap** [comment]
I've just clone it, it's better, but it's still quite big, E.g. there are pdf files in the history:

![pic](https://cloud.githubusercontent.com/assets/39654/14361472/61712624-fcd1-11e5-9f66-2ede71a5c923.png)

Why not you just remove the whole Docs/ folder history and commit the Doxyfile at the end with a new commit?

**Comment by LB--** [comment]
@dacap I can fix it, I didn't realize there were still PDFs. Got an example commit I can look at for reference?

**Comment by dacap** [comment]
77ff17eb914cd553aa032934d7f76497d13f7bdf

**Comment by LB--** [comment]
@dacap Oh, that's not a commit in the master branch - that's a tag that will have to be manually moved to the new correct commit. @ziacko has to move the tags himself - have a look at http://stackoverflow.com/a/8044605/1959975 - you'll have to find the corresponding commit for each tag you have. Unfortunately I don't know of a faster way to do this, sorry :(

**Comment by ziacko** [comment]
ok couldnt I just delete the tags altogether? Or do i have to go one by one and push the chages individually?

**Comment by LB--** [comment]
@ziacko you could, that's up to you. It would be a tedious process to move them all individually, but you do still have to delete them individually. You could also just leave them and tell people not to use them. I wish I could do something to help but I really don't know the best course of action here.

**Comment by ziacko** [comment]
ok they're all gone. after they tags were deleted the duplicate commits disappeared which filled me with joy haha. It's now down to 6.99 Mb's. Now I'm going to sleep coz it's 4:30 AM here right now and my brain is fried
