### ISSUE TITLE
On linux line 1900: else with no previous if

### ISSUE THREAD

**Issue by rivenblades** [ziacko/TinyWindow#29]
You have error, else is without if , if we are on linux platform
I changed that and put else in the #ifdef windows.
But when i run the Example.cpp, when i press space it gets segmentation fault

**Comment by ziacko** [comment]
ok. I'll get on that after I finish adding the features I want on the Windows side. after that I will fix Linux issues and make sure it has parity with the windows side

**Comment by michael-hardeman** [comment]
I have opened a PR for to fix this issue
https://github.com/ziacko/TinyWindow/pull/31

I only applied a band-aid `if (0) {}` for now, but at least the program builds and opens a window.

**Comment by ziacko** [comment]
fix has been solved, code now compiles properly on Linux
