### ISSUE TITLE
Example project fails build on Linux

### ISSUE THREAD

**Issue by alternative16** [ziacko/TinyWindow#30]
I am using Arch linux and i tried building the example project. I get the following errors from TinyWindow.h
[errors.txt](https://github.com/ziacko/TinyWindow/files/7130416/errors.txt)
I get the same errors in any project where I use TinyWindow.

Thanks for the help!

**Comment by michael-hardeman** [comment]
I have opened a PR to fix these issues.
https://github.com/ziacko/TinyWindow/pull/31

**Comment by ziacko** [comment]
compilation issue has been fixed with latest commits
