### ISSUE TITLE
Multiple monitors?

### ISSUE THREAD

**Issue by refi64** [ziacko/TinyWindow#9]
SFML has virtually _no_ support for multiple monitors or monitor detection. I was just wondering, would it be possible to add something like this to TinyWindow? Some sort of API to determine which monitor a window geta drawn onto?

**Comment by ziacko** [comment]
I'll look into it. It has been on my trello for a while now

**Comment by ziacko** [comment]
ok for clarification can we develop a quick list of features you want in this area. I like to work in to-do lists if you don't mind. I tend to use Trello or Google Keep to help me keep track

**Comment by refi64** [comment]
Sure! What I was thinking was something like:
- Add a function to get the number of monitors.
- Add an integer argument to `SetFullScreen` that determines the monitor on which to make the window fullscreen, or `-1` to leave the current one.

**Comment by ziacko** [comment]
ok cool. what about moving the windows. I changed the parameters for moving windows from unsigned to signed int to allow rudimentary multi screen support. would you like another parameter to pick and choose which monitor?

**Comment by ziacko** [comment]
btw I only have one moniter at home So I have to do a few dodgy hacks just to test the code haha

**Comment by refi64** [comment]
That sounds great!

**Comment by ziacko** [comment]
I've also been thinking about giving users a list of display settings i.e. "1920 x 1080", etc. I think that could help alot when trying to get the best window sizes for a selected monitor. in X11 its neccessary and I think saving that info and making it publicly available could reallly help

**Comment by ziacko** [comment]
Hey I've made an update in experimental branch for multi monitor fullscreen support. tell me if something is missing. Right now it's only for windows. https://github.com/ziacko/TinyWindow/tree/experimental
